apiVersion: apps/v1
kind: Deployment
metadata:
  name: awsbatch
  labels:
    app: awsbatch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awsbatch
  template:
    metadata:
      labels:
        app: awsbatch
    spec:
      containers:
      - name: awsbatch
        image: kokkulasaiteja/testsample
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: awsbatch
  labels:
    app: awsbatch
spec:
  selector:
    app: awsbatch  
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080 
